#!/usr/bin/env node
/**
 * Generates the production service worker (dist/sw.js) after Astro builds.
 * Scans the dist directory and creates a self-contained service worker
 * with precaching, runtime caching, and offline fallback — no external deps.
 *
 * The cache version is derived from the precache content, so every deploy
 * produces a new cache namespace and the activate handler purges stale ones.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { createHash } from 'node:crypto';

const distDir = new URL('../dist', import.meta.url).pathname;

// Collect all files to precache (everything Astro generated except sw.js itself)
async function collectFiles(dir) {
	const results = [];
	const entries = await readdir(dir, { withFileTypes: true });
	for (const entry of entries) {
		const fullPath = join(dir, entry.name);
		if (entry.name === 'sw.js') continue; // don't cache the SW itself
		if (entry.isDirectory()) {
			results.push(...(await collectFiles(fullPath)));
		} else {
			results.push(fullPath);
		}
	}
	return results;
}

const files = await collectFiles(distDir);

// Build precache manifest: [url, revisionHash]
const precacheEntries = [];
for (const filePath of files) {
	const urlPath = '/' + relative(distDir, filePath).split(sep).join('/');
	let revision = '';
	try {
		const content = await readFile(filePath);
		revision = createHash('md5').update(content).digest('hex').slice(0, 8);
	} catch {
		revision = Date.now().toString(36);
	}
	precacheEntries.push({ url: urlPath, revision });
}

// Content-derived cache version → bumps the cache namespace on every deploy
const versionHash = createHash('md5')
	.update(JSON.stringify(precacheEntries))
	.digest('hex')
	.slice(0, 8);

const precacheManifest = JSON.stringify(precacheEntries);

const swSource = `/* iPrep Pro Service Worker — auto-generated by scripts/generate-sw.js */
const CACHE_VERSION = 'v${versionHash}';
const PRECACHE = ${precacheManifest};
const DATA_CACHE = 'iprep-data-' + CACHE_VERSION;
const ASSET_CACHE = 'iprep-assets-' + CACHE_VERSION;
const PAGE_CACHE = 'iprep-pages-' + CACHE_VERSION;
const OFFLINE_PAGE = '/offline.html';

// --- Install: pre-cache all built files (per-file, so one failure can't
// --- brick the whole install) ---
self.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(PAGE_CACHE)
			.then((cache) =>
				Promise.all(
					PRECACHE.map((entry) =>
						cache.add(entry.url).catch(() => null)
					)
				)
			)
			.then(() => self.skipWaiting())
			.catch((err) => console.error('[PWA] Install failed:', err))
	);
});

// --- Activate: clean up old caches ---
self.addEventListener('activate', (event) => {
	const currentCaches = [PAGE_CACHE, DATA_CACHE, ASSET_CACHE];
	event.waitUntil(
		caches
			.keys()
			.then((cacheNames) =>
				Promise.all(
					cacheNames.map((cacheName) => {
						if (!currentCaches.includes(cacheName)) {
							return caches.delete(cacheName);
						}
						return null;
					})
				)
			)
			.then(() => self.clients.claim())
	);
});

// --- Helper: Network first, then cache, then offline ---
async function networkFirst(request, cacheName) {
	try {
		const response = await fetch(request);
		if (response.ok) {
			const cache = await caches.open(cacheName);
			cache.put(request, response.clone());
		}
		return response;
	} catch {
		const cached = await caches.match(request);
		if (cached) return cached;
		if (cacheName === PAGE_CACHE) {
			return caches.match(OFFLINE_PAGE);
		}
		return new Response('', { status: 504, statusText: 'Gateway Timeout' });
	}
}

// --- Helper: Cache first, then network ---
async function cacheFirst(request, cacheName) {
	const cached = await caches.match(request);
	if (cached) return cached;
	const response = await fetch(request);
	if (response.ok && response.type === 'basic') {
		const cache = await caches.open(cacheName);
		cache.put(request, response.clone());
	}
	return response;
}

// --- Fetch: route-based caching strategies ---
self.addEventListener('fetch', (event) => {
	const { request } = event;
	const url = new URL(request.url);

	// Only handle same-origin requests
	if (url.origin !== self.location.origin) return;

	// Skip non-GET requests
	if (request.method !== 'GET') return;

	// Navigation requests (HTML pages): NetworkFirst with offline fallback
	if (request.mode === 'navigate') {
		event.respondWith(networkFirst(request, PAGE_CACHE));
		return;
	}

	// API / data JSON: CacheFirst (these often in a static site)
	if (
		url.pathname.startsWith('/api/questions/') ||
		url.pathname.startsWith('/search-index.json')
	) {
		event.respondWith(cacheFirst(request, DATA_CACHE));
		return;
	}

	// Static assets (images, styles, scripts, fonts): CacheFirst
	if (
		request.destination === 'image' ||
		request.destination === 'style' ||
		request.destination === 'script' ||
		request.destination === 'font'
	) {
		event.respondWith(cacheFirst(request, ASSET_CACHE));
		return;
	}

	// Everything else: network passthrough
});

// --- Listen for messages to trigger updates ---
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting();
	}
});
`;

await writeFile(join(distDir, 'sw.js'), swSource);

console.log(
	`[PWA] Service worker generated — ${precacheEntries.length} files pre-cached (v${versionHash})`
);